server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@gang-soldesk-nam.tplinkdns.com:15271:xe
    username: gldj
    password: gldj
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: -1
      location: D:/Soldesk/Video

  security:
    user:
      name: test
      password: 1234
    
  jackson:
    serialization:
      fail-on-empty-beans: false
      
file:
  path: C:/Temp
  pathvideo: D:/Soldesk/Video

